### ISSUE TITLE
Switching between front and back camera

### ISSUE THREAD

**Issue by timlenardo** [JohnnySlagle/Multiple-Camera-Feeds#1]
Hey Johnny,

Thanks for the repro - this was really useful in getting a GL project up and running. 

Right now I'm trying to switch between the front and back cameras and still have a live preview. Is this possible with the framework you've presented?

Sorry, this isn't quite an 'issue' - I wasn't sure how to get in contact with you.

**Comment by timlenardo** [comment]
Figured this out. For posterity, you can totally re-instantiate the views and GL context by adding a method like:

-(void)restartView {
    _captureSession = nil;
    _captureSessionQueue = nil;
    _ciContext = nil;
    _eaglContext = nil;

```
// Remove all the preview surfaces
for (GLKViewWithBounds *feedView in self.feedViews) {
    [feedView removeFromSuperview];
}

[self viewDidLoad];
```

}

Then you just need to set a 'frontCamera' flag, and choose either AVCaptureDevice 0 or 1 (back or front) accordingly in 'setupSession'.

**Comment by JohnnySlagle** [comment]
Dude, nice! Sorry I with the delay in response. I haven't really checked github in a long time being with what's up at work.
